import Image from "next/image";
import "./globals.css";
import localFont from "next/font/local";
import logoHeader from "../assets/somefunLogoHeader.png";
import Insta from "@/components/icons/insta";
import Linkedin from "@/components/icons/linkedin";
import HeaderCarousel from "./HeaderCarousel";

const kumbh = localFont({
  src: [
    { path: "../../public/fonts/kumbh/KumbhSans-Thin.ttf", weight: "100" },
    {
      path: "../../public/fonts/kumbh/KumbhSans-ExtraLight.ttf",
      weight: "200",
    },
    { path: "../../public/fonts/kumbh/KumbhSans-Light.ttf", weight: "300" },
    { path: "../../public/fonts/kumbh/KumbhSans-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/kumbh/KumbhSans-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/kumbh/KumbhSans-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/kumbh/KumbhSans-Bold.ttf", weight: "700" },
    { path: "../../public/fonts/kumbh/KumbhSans-ExtraBold.ttf", weight: "800" },
    { path: "../../public/fonts/kumbh/KumbhSans-Black.ttf", weight: "900" },
  ],
  variable: "--font-kumbh",
});
const marshland = localFont({
  src: [
    {
      path: "../../public/fonts/marshland/Marshland_Beauty.ttf",
      weight: "400",
    },
  ],
  variable: "--font-marshland",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItem = "px-6 py-2";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kumbh.variable} ${marshland.variable} font-sans`}>
        <HeaderCarousel />
        <header className="sticky top-0">
          <nav className="px-12 h-[80px] flex justify-between items-center relative bg-landing">
            <ul className="flex text-seaweed font-medium">
              <li className={`${navItem}`}>HOME</li>
              <li className={`${navItem}`}>SERVICES</li>
              <li className={`${navItem}`}>WORK</li>
              <li className={`${navItem}`}>ABOUT</li>
            </ul>
            <Image
              className="w-[164px] h-auto absolute top-[50%] left-[50%] -translate-x-[50%] -translate-y-[50%]"
              src={logoHeader}
              alt="some fun logo"
            />
            <div className="flex items-center gap-4">
              <Linkedin />
              <Insta />
            </div>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
