import Image from "next/image";
import "./globals.css";
import localFont from "next/font/local";
import logoHeader from "../assets/somefunLogoHeader.png";
import Insta from "../components/icons/insta";
import Linkedin from "../components/icons/linkedin";
import HeaderCarousel from "./HeaderCarousel";
import NavItem from "./NavItem";
import Footer from "./Footer.jsx";

const kumbh = localFont({
  src: [
    { path: "../../public/fonts/kumbh/KumbhSans-Thin.ttf", weight: "100" },
    {
      path: "../../public/fonts/kumbh/KumbhSans-ExtraLight.ttf",
      weight: "200",
    },
    { path: "../../public/fonts/kumbh/KumbhSans-Light.ttf", weight: "300" },
    { path: "../../public/fonts/kumbh/KumbhSans-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/kumbh/KumbhSans-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/kumbh/KumbhSans-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/kumbh/KumbhSans-Bold.ttf", weight: "700" },
    { path: "../../public/fonts/kumbh/KumbhSans-ExtraBold.ttf", weight: "800" },
    { path: "../../public/fonts/kumbh/KumbhSans-Black.ttf", weight: "900" },
  ],
  variable: "--font-kumbh",
});
const marshland = localFont({
  src: [
    {
      path: "../../public/fonts/marshland/Marshland_Beauty.ttf",
      weight: "400",
    },
  ],
  variable: "--font-marshland",
});
const bavistage = localFont({
  src: [
    {
      path: "../../public/fonts/bavistage/bavistage.otf",
      weight: "400",
    },
  ],
  variable: "--font-bavistage",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kumbh.variable} ${marshland.variable} ${bavistage.variable} isolate font-sans`}
      >
        <HeaderCarousel
          message={"NOW BOOKING PROJECTS FOR 2023"}
          width={366}
          animation={"animate-slowSlideHeader"}
        />
        <header className="sticky top-0 z-40">
          <nav className="relative flex h-[80px] items-center justify-between bg-landingBg bg-landing px-12">
            <ul className="flex font-medium text-seaweed">
              <NavItem pathClass="stroke-burnt" text="HOME" path="/" exact />
              <NavItem
                pathClass="stroke-strokePinky navItemServices"
                text="SERVICES"
                path="/services"
              />
              <NavItem pathClass="stroke-darkDijon" text="WORK" path="/work" />
              <NavItem pathClass="stroke-seaweed" text="ABOUT" path="/about" />
            </ul>
            <Image
              className="absolute left-[50%] top-[50%] h-auto w-[164px] -translate-x-[50%] -translate-y-[50%]"
              src={logoHeader}
              alt="some fun logo"
            />
            <div className="flex items-center gap-4">
              <Linkedin />
              <Insta />
            </div>
          </nav>
        </header>
        <main className="flex justify-center bg-pale">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
